// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDuG4G447zyWYxN2H6z6BGyeop3FsUTM',
    appId: '1:369185878608:web:ff35721272899a1e2c9755',
    messagingSenderId: '369185878608',
    projectId: 'ecommerce-0101-b65ee',
    authDomain: 'ecommerce-0101-b65ee.firebaseapp.com',
    storageBucket: 'ecommerce-0101-b65ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycu5Hzdjlk53l2PPCnpCm86jh9SwCMbk',
    appId: '1:369185878608:android:bb13044d4d320e102c9755',
    messagingSenderId: '369185878608',
    projectId: 'ecommerce-0101-b65ee',
    storageBucket: 'ecommerce-0101-b65ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0de0IfFRT1MPnUZzz1gxYjzXQplwMCM',
    appId: '1:369185878608:ios:1851120138213b062c9755',
    messagingSenderId: '369185878608',
    projectId: 'ecommerce-0101-b65ee',
    storageBucket: 'ecommerce-0101-b65ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignmentY4S1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ0de0IfFRT1MPnUZzz1gxYjzXQplwMCM',
    appId: '1:369185878608:ios:1851120138213b062c9755',
    messagingSenderId: '369185878608',
    projectId: 'ecommerce-0101-b65ee',
    storageBucket: 'ecommerce-0101-b65ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignmentY4S1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlDuG4G447zyWYxN2H6z6BGyeop3FsUTM',
    appId: '1:369185878608:web:24e24bd784c347252c9755',
    messagingSenderId: '369185878608',
    projectId: 'ecommerce-0101-b65ee',
    authDomain: 'ecommerce-0101-b65ee.firebaseapp.com',
    storageBucket: 'ecommerce-0101-b65ee.firebasestorage.app',
  );
}
